// coin data
export const FETCH_COIN = 'FETCH_COIN';

// coin filters
export const SORT_BY_NAME_ASCENDING = 'SORT_BY_NAME_ASCENDING';
export const SORT_BY_AMOUNT_ASCENDING = 'SORT_BY_AMOUNT_ASCENDING';
export const SORT_BY_AMOUNT_DESCENDING = 'SORT_BY_AMOUNT_DESCENDING';
export const SORT_BY_NAME_DESCENDING = 'SORT_BY_NAME_DESCENDING';
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
