// coin data
export const FETCH_COIN = 'FETCH_COIN';
export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP';

// coin filters
export const SORT_BY_NAME_ASCENDING = 'SORT_BY_NAME_ASCENDING';
export const SORT_BY_NAME_DESCENDING = 'SORT_BY_NAME_DESCENDING';
export const SORT_BY_PRICE_USD_ASCENDING = 'SORT_BY_PRICE_USD_ASCENDING';
export const SORT_BY_PRICE_USD_DESCENDING = 'SORT_BY_PRICE_USD_DESCENDING';
export const SORT_BY_MARKET_CAP_ASCENDING = 'SORT_BY_MARKET_CAP_ASCENDING';
export const SORT_BY_MARKET_CAP_DESCENDING = 'SORT_BY_MARKET_CAP_DESCENDING';
export const SORT_BY_PER_CHANGE_ASCENDING = 'SORT_BY_PER_CHANGE_ASCENDING';
export const SORT_BY_PER_CHANGE_DESCENDING = 'SORT_BY_PER_CHANGE_DESCENDING';
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
